site_name: AlexaVoxCraft
site_description: Modular C# .NET library for building Amazon Alexa skills
site_url: https://layeredcraft.github.io/alexa-vox-craft/
site_author: LayeredCraft Team

# Repository
repo_name: LayeredCraft/alexa-vox-craft
repo_url: https://github.com/LayeredCraft/alexa-vox-craft
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 LayeredCraft Team

# Configuration
theme:
  name: material
  language: en
  logo: assets/icon.png
  favicon: assets/icon.png
  
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  # Dark/Light mode toggle
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Components:
    - Request Handling: components/request-handling.md
    - APL Integration: components/apl-integration.md
    - Lambda Hosting: components/lambda-hosting.md
    - Session Management: components/session-management.md
    - Pipeline Behaviors: components/pipeline-behaviors.md
    - Source Generators: components/source-generation.md
  - Examples: examples/index.md

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LayeredCraft/alexa-vox-craft
      name: GitHub Repository
    - icon: fontawesome/solid/download
      link: https://www.nuget.org/packages/AlexaVoxCraft.MediatR.Lambda/
      name: NuGet Package