<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks></TargetFrameworks>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Using Remove="Xunit" />
        <Using Remove="AwesomeAssertions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AlexaVoxCraft.Lambda\AlexaVoxCraft.Lambda.csproj" />
        <ProjectReference Include="..\..\src\AlexaVoxCraft.MediatR\AlexaVoxCraft.MediatR.csproj" />
        <ProjectReference Include="..\..\src\AlexaVoxCraft.Model\AlexaVoxCraft.Model.csproj" />
    </ItemGroup>

</Project>
