//HintName: __AlexaVoxCraft_Interceptors.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AlexaVoxCraft.Generated
{
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

file static class AlexaVoxCraftInterceptors
{
    [InterceptsLocation(version: 1, data: "4U7ZzrlxZdbQFegpnC9ceMoBAABGdW5jdGlvbi5jcw==")]
    internal static IServiceCollection AddSkillMediator(
        this IServiceCollection services,
        IConfiguration configuration,
        Action<AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration>? settingsAction = null,
        string sectionName = AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration.SectionName)
    {
        // Build effective configuration
        var cfg = new AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration();
        configuration.GetSection(sectionName).Bind(cfg);
        settingsAction?.Invoke(cfg);

        // Register configuration with DI to enable IOptions<SkillServiceConfiguration>
        services.Configure<AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration>(opt =>
        {
            configuration.GetSection(sectionName).Bind(opt);
            settingsAction?.Invoke(opt);
        });

        // Add required core services
        AlexaVoxCraft.MediatR.Registration.ServiceRegistrar.AddRequiredServices(services, cfg);

        // Request Handlers
        services.AddSingleton<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.SessionEndedRequest>, global::Sample.Generated.Function.SessionEndedHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Request.Type.SessionEndedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Request.Type.SessionEndedRequest>());
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.LaunchRequest>, global::Sample.Generated.Function.LaunchTriviaHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Request.Type.LaunchRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Request.Type.LaunchRequest>());
        services.AddScoped<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.IntentRequest>, global::Sample.Generated.Function.AnswerHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Request.Type.IntentRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Request.Type.IntentRequest>());
        services.AddScoped<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Apl.UserEventRequest>, global::Sample.Generated.Function.AnswerHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Apl.UserEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Apl.UserEventRequest>());
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.IntentRequest>, global::Sample.Generated.Function.HelpIntentHandler>();
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.IntentRequest>, global::Sample.Generated.Function.RepeatIntentHandler>();
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.IntentRequest>, global::Sample.Generated.Function.StopOrCancelHandler>();
        services.TryAddTransient<AlexaVoxCraft.MediatR.IDefaultRequestHandler, global::Sample.Generated.Function.DefaultTriviaHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.IntentRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.IntentRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.LaunchRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.LaunchRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SessionEndedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SessionEndedRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SystemExceptionRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SystemExceptionRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.AudioPlayerRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.AudioPlayerRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.PlaybackControllerRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.PlaybackControllerRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.DisplayElementSelectedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.DisplayElementSelectedRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.AccountLinkSkillEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.AccountLinkSkillEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.PermissionSkillEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.PermissionSkillEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SkillEnablementSkillEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SkillEnablementSkillEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SkillEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SkillEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SessionResumedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SessionResumedRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.AskForPermissionRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.AskForPermissionRequest>());

        // Exception Handlers
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IExceptionHandler, global::Sample.Generated.Function.TriviaExceptionHandler>();

        // Request Interceptors
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IRequestInterceptor, global::Sample.Generated.Function.LanguageRequestInterceptor>();
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IRequestInterceptor, global::Sample.Generated.Function.LoggingInterceptor>();

        // Response Interceptors
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IResponseInterceptor, global::Sample.Generated.Function.LoggingInterceptor>();
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IResponseInterceptor, global::Sample.Generated.Function.SaveDataResponseInterceptor>();

        // Persistence Adapter
        services.TryAddSingleton<AlexaVoxCraft.MediatR.Attributes.Persistence.IPersistenceAdapter, global::Sample.Generated.Function.DynamoDbTriviaAdapter>();

        return services;
    }
}
}
