//HintName: __AlexaVoxCraft_Interceptors.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AlexaVoxCraft.Generated
{
using System;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

file static class AlexaVoxCraftInterceptors
{
    [InterceptsLocation(version: 1, data: "4U7ZzrlxZdbQFegpnC9ceMoBAABGdW5jdGlvbi5jcw==")]
    internal static IServiceCollection AddSkillMediator(
        this IServiceCollection services,
        IConfiguration configuration,
        Action<AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration>? settingsAction = null,
        string sectionName = AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration.SectionName)
    {
        // Build effective configuration
        var cfg = new AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration();
        BindSkillServiceConfiguration(configuration.GetSection(sectionName), cfg);
        settingsAction?.Invoke(cfg);

        // Register configuration with DI to enable IOptions<SkillServiceConfiguration>
        services.Configure<AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration>(opt =>
        {
            BindSkillServiceConfiguration(configuration.GetSection(sectionName), opt);
            settingsAction?.Invoke(opt);
        });

        // Add required core services
        AlexaVoxCraft.MediatR.Registration.ServiceRegistrar.AddRequiredServices(services, cfg);

        // Request Handlers
        services.AddSingleton<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.SessionEndedRequest>, global::Sample.Generated.Function.SessionEndedHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Request.Type.SessionEndedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Request.Type.SessionEndedRequest>());
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.LaunchRequest>, global::Sample.Generated.Function.LaunchTriviaHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Request.Type.LaunchRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Request.Type.LaunchRequest>());
        services.AddScoped<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.IntentRequest>, global::Sample.Generated.Function.AnswerHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Request.Type.IntentRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Request.Type.IntentRequest>());
        services.AddScoped<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Apl.UserEventRequest>, global::Sample.Generated.Function.AnswerHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Apl.UserEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Apl.UserEventRequest>());
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.IntentRequest>, global::Sample.Generated.Function.HelpIntentHandler>();
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.IntentRequest>, global::Sample.Generated.Function.RepeatIntentHandler>();
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.IntentRequest>, global::Sample.Generated.Function.StopOrCancelHandler>();
        services.TryAddTransient<AlexaVoxCraft.MediatR.IDefaultRequestHandler, global::Sample.Generated.Function.DefaultTriviaHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.DataStore.DataStoreErrorRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.DataStore.DataStoreErrorRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.DataStore.PackageManager.InstallationError), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.DataStore.PackageManager.InstallationError>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.DataStore.PackageManager.UpdateRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.DataStore.PackageManager.UpdateRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.DataStore.PackageManager.UsagesInstalledRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.DataStore.PackageManager.UsagesInstalledRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.DataStore.PackageManager.UsagesRemovedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.DataStore.PackageManager.UsagesRemovedRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.LoadIndexListDataRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.LoadIndexListDataRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.LoadTokenListDataRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.LoadTokenListDataRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.RuntimeErrorRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.RuntimeErrorRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Apl.UserEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Apl.UserEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.AccountLinkSkillEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.AccountLinkSkillEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.AskForPermissionRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.AskForPermissionRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.AudioPlayerRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.AudioPlayerRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.DisplayElementSelectedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.DisplayElementSelectedRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.IntentRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.IntentRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.LaunchRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.LaunchRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.PermissionSkillEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.PermissionSkillEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.PlaybackControllerRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.PlaybackControllerRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SessionEndedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SessionEndedRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SessionResumedRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SessionResumedRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SkillEnablementSkillEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SkillEnablementSkillEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SkillEventRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SkillEventRequest>());
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(global::AlexaVoxCraft.Model.Request.Type.SystemExceptionRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<global::AlexaVoxCraft.Model.Request.Type.SystemExceptionRequest>());

        // Exception Handlers
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IExceptionHandler, global::Sample.Generated.Function.TriviaExceptionHandler>();

        // Request Interceptors
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IRequestInterceptor, global::Sample.Generated.Function.LanguageRequestInterceptor>();
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IRequestInterceptor, global::Sample.Generated.Function.LoggingInterceptor>();

        // Response Interceptors
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IResponseInterceptor, global::Sample.Generated.Function.LoggingInterceptor>();
        services.AddTransient<AlexaVoxCraft.MediatR.Pipeline.IResponseInterceptor, global::Sample.Generated.Function.SaveDataResponseInterceptor>();

        // Persistence Adapter
        services.TryAddSingleton<AlexaVoxCraft.MediatR.Attributes.Persistence.IPersistenceAdapter, global::Sample.Generated.Function.DynamoDbTriviaAdapter>();

        return services;
    }

    private static void BindSkillServiceConfiguration(IConfigurationSection section, AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration target)
    {
        var customUserAgent = section["CustomUserAgent"];
        if (customUserAgent is not null)
        {
            target.CustomUserAgent = customUserAgent;
        }

        var skillId = section["SkillId"];
        if (skillId is not null)
        {
            target.SkillId = skillId;
        }

        var defaultVoiceName = section["DefaultVoiceName"];
        if (defaultVoiceName is not null)
        {
            target.DefaultVoiceName = defaultVoiceName;
        }

        var lifetime = section["Lifetime"];
        if (lifetime is not null)
        {
            target.Lifetime = Enum.Parse<Microsoft.Extensions.DependencyInjection.ServiceLifetime>(lifetime, ignoreCase: true);
        }

        var cancellationTimeoutBufferMilliseconds = section["CancellationTimeoutBufferMilliseconds"];
        if (cancellationTimeoutBufferMilliseconds is not null)
        {
            target.CancellationTimeoutBufferMilliseconds = int.Parse(cancellationTimeoutBufferMilliseconds, CultureInfo.InvariantCulture);
        }
    }

}
}
