//HintName: __AlexaVoxCraft_Interceptors.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace AlexaVoxCraft.Generated
{
using System;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

file static class AlexaVoxCraftInterceptors
{
    [InterceptsLocation(version: 1, data: "mLyvHdhJXdfwcGbMlslMjMoBAABGdW5jdGlvbi5jcw==")]
    internal static IServiceCollection AddSkillMediator(
        this IServiceCollection services,
        IConfiguration configuration,
        Action<AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration>? settingsAction = null,
        string sectionName = AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration.SectionName)
    {
        // Build effective configuration
        var cfg = new AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration();
        BindSkillServiceConfiguration(configuration.GetSection(sectionName), cfg);
        settingsAction?.Invoke(cfg);

        // Register configuration with DI to enable IOptions<SkillServiceConfiguration>
        services.Configure<AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration>(opt =>
        {
            BindSkillServiceConfiguration(configuration.GetSection(sectionName), opt);
            settingsAction?.Invoke(opt);
        });

        // Add required core services
        AlexaVoxCraft.MediatR.Registration.ServiceRegistrar.AddRequiredServices(services, cfg);

        // Request Handlers
        services.AddTransient<AlexaVoxCraft.MediatR.IRequestHandler<AlexaVoxCraft.Model.Request.Type.LaunchRequest>, global::Referenced.NoIvt.PublicReferencedLaunchHandler>();
        services.AddKeyedSingleton<AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapper>(typeof(AlexaVoxCraft.Model.Request.Type.LaunchRequest), (sp, key) => new AlexaVoxCraft.MediatR.Wrappers.RequestHandlerWrapperImpl<AlexaVoxCraft.Model.Request.Type.LaunchRequest>());

        return services;
    }

    private static void BindSkillServiceConfiguration(IConfigurationSection section, AlexaVoxCraft.MediatR.DI.SkillServiceConfiguration target)
    {
        var customUserAgent = section["CustomUserAgent"];
        if (customUserAgent is not null)
        {
            target.CustomUserAgent = customUserAgent;
        }

        var skillId = section["SkillId"];
        if (skillId is not null)
        {
            target.SkillId = skillId;
        }

        var defaultVoiceName = section["DefaultVoiceName"];
        if (defaultVoiceName is not null)
        {
            target.DefaultVoiceName = defaultVoiceName;
        }

        var lifetime = section["Lifetime"];
        if (lifetime is not null)
        {
            target.Lifetime = Enum.Parse<Microsoft.Extensions.DependencyInjection.ServiceLifetime>(lifetime, ignoreCase: true);
        }

        var cancellationTimeoutBufferMilliseconds = section["CancellationTimeoutBufferMilliseconds"];
        if (cancellationTimeoutBufferMilliseconds is not null)
        {
            target.CancellationTimeoutBufferMilliseconds = int.Parse(cancellationTimeoutBufferMilliseconds, CultureInfo.InvariantCulture);
        }
    }

}
}
