using System.Text.Json.Serialization;
using AlexaVoxCraft.Model.Apl.Commands;
using AlexaVoxCraft.Model.Apl.Components;
using AlexaVoxCraft.Model.Apl.Gestures;

namespace AlexaVoxCraft.Model.Apl.Serialization;

/// <summary>
/// JSON source generation context for all APL (Alexa Presentation Language) types.
/// This provides compile-time JSON serialization for improved Lambda cold start performance.
/// </summary>
[JsonSourceGenerationOptions(
    GenerationMode = JsonSourceGenerationMode.Default,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
// Core APL document types
[JsonSerializable(typeof(APLDocument))]
[JsonSerializable(typeof(APLADocument))]
[JsonSerializable(typeof(APLTDocument))]
[JsonSerializable(typeof(APLDocumentBase))]
[JsonSerializable(typeof(RenderDocumentDirective))]
[JsonSerializable(typeof(ExecuteCommandsDirective))]
// Core APL components
[JsonSerializable(typeof(APLComponent))]
[JsonSerializable(typeof(APLComponentBase))]
[JsonSerializable(typeof(Container))]
[JsonSerializable(typeof(Text))]
[JsonSerializable(typeof(TextBase))]
[JsonSerializable(typeof(Image))]
[JsonSerializable(typeof(Frame))]
[JsonSerializable(typeof(Sequence))]
[JsonSerializable(typeof(Pager))]
[JsonSerializable(typeof(ScrollView))]
[JsonSerializable(typeof(GridSequence))]
[JsonSerializable(typeof(TouchWrapper))]
[JsonSerializable(typeof(VectorGraphic))]
[JsonSerializable(typeof(Video))]
[JsonSerializable(typeof(EditText))]
[JsonSerializable(typeof(CustomComponent))]
[JsonSerializable(typeof(ResponsiveTemplate))]
[JsonSerializable(typeof(TouchComponent))]
// Alexa Design System Components
[JsonSerializable(typeof(AlexaHeader))]
[JsonSerializable(typeof(AlexaFooter))]
[JsonSerializable(typeof(AlexaButton))]
[JsonSerializable(typeof(AlexaCard))]
[JsonSerializable(typeof(AlexaImage))]
[JsonSerializable(typeof(AlexaIcon))]
[JsonSerializable(typeof(AlexaIconButton))]
[JsonSerializable(typeof(AlexaBackground))]
[JsonSerializable(typeof(AlexaDivider))]
[JsonSerializable(typeof(AlexaDetail))]
[JsonSerializable(typeof(AlexaHeadline))]
[JsonSerializable(typeof(AlexaTextList))]
[JsonSerializable(typeof(AlexaTextListItem))]
[JsonSerializable(typeof(AlexaImageList))]
[JsonSerializable(typeof(AlexaImageListBase))]
[JsonSerializable(typeof(AlexaImageListItem))]
[JsonSerializable(typeof(AlexaPaginatedList))]
[JsonSerializable(typeof(AlexaPaginatedListItem))]
[JsonSerializable(typeof(AlexaListItem))]
[JsonSerializable(typeof(AlexaLists))]
[JsonSerializable(typeof(AlexaGridList))]
[JsonSerializable(typeof(AlexaOrdinal))]
[JsonSerializable(typeof(AlexaPageCounter))]
[JsonSerializable(typeof(AlexaPhoto))]
[JsonSerializable(typeof(AlexaProgressBar))]
[JsonSerializable(typeof(AlexaProgressBarBase))]
[JsonSerializable(typeof(AlexaProgressBarRadial))]
[JsonSerializable(typeof(AlexaProgressDots))]
[JsonSerializable(typeof(AlexaSlider))]
[JsonSerializable(typeof(AlexaSliderBase))]
[JsonSerializable(typeof(AlexaSliderRadial))]
[JsonSerializable(typeof(AlexaRating))]
[JsonSerializable(typeof(AlexaCheckbox))]
[JsonSerializable(typeof(AlexaRadioButton))]
[JsonSerializable(typeof(AlexaSwitch))]
[JsonSerializable(typeof(AlexaSwipeToAction))]
[JsonSerializable(typeof(AlexaTransportControls))]
[JsonSerializable(typeof(AlexaImageCaption))]
// APL Commands
[JsonSerializable(typeof(APLCommand))]
[JsonSerializable(typeof(AnimateItem))]
[JsonSerializable(typeof(AutoPage))]
[JsonSerializable(typeof(ClearFocus))]
[JsonSerializable(typeof(ControlMedia))]
[JsonSerializable(typeof(CustomCommand))]
[JsonSerializable(typeof(Finish))]
[JsonSerializable(typeof(Idle))]
[JsonSerializable(typeof(InsertItem))]
[JsonSerializable(typeof(OpenURL))]
[JsonSerializable(typeof(Parallel))]
[JsonSerializable(typeof(PlayMedia))]
[JsonSerializable(typeof(Reinflate))]
[JsonSerializable(typeof(RemoveItem))]
[JsonSerializable(typeof(Scroll))]
[JsonSerializable(typeof(ScrollToComponent))]
[JsonSerializable(typeof(ScrollToIndex))]
[JsonSerializable(typeof(Select))]
[JsonSerializable(typeof(SendEvent))]
[JsonSerializable(typeof(Sequential))]
[JsonSerializable(typeof(SetFocus))]
[JsonSerializable(typeof(SetPage))]
[JsonSerializable(typeof(SetValue))]
[JsonSerializable(typeof(SpeakItem))]
[JsonSerializable(typeof(SpeakList))]
// APL Animation Commands
[JsonSerializable(typeof(AnimatedOpacity))]
[JsonSerializable(typeof(AnimatedProperty))]
[JsonSerializable(typeof(AnimatedTransform))]
// APL Command supporting types
[JsonSerializable(typeof(CommandDefinition))]
[JsonSerializable(typeof(APLCommandSource))]
[JsonSerializable(typeof(SetPagePosition))]
[JsonSerializable(typeof(SetStateStates))]
// APL Values and Dimensions
[JsonSerializable(typeof(APLValue))]
[JsonSerializable(typeof(APLDimensionValue))]
[JsonSerializable(typeof(APLAbsoluteDimensionValue))]
// APL Gestures
[JsonSerializable(typeof(APLGesture))]
[JsonSerializable(typeof(DoublePress))]
[JsonSerializable(typeof(LongPress))]
[JsonSerializable(typeof(SwipeAway))]
[JsonSerializable(typeof(Tap))]
// APL Supporting types
[JsonSerializable(typeof(APLAction))]
[JsonSerializable(typeof(APLContext))]
[JsonSerializable(typeof(APLDataSource))]
[JsonSerializable(typeof(APLDisplay))]
[JsonSerializable(typeof(APLDocumentEnvironment))]
[JsonSerializable(typeof(APLDocumentLink))]
[JsonSerializable(typeof(APLDocumentReference))]
[JsonSerializable(typeof(APLDocumentSettings))]
[JsonSerializable(typeof(APLDocumentVersion))]
[JsonSerializable(typeof(APLError))]
[JsonSerializable(typeof(APLExtension))]
[JsonSerializable(typeof(APLGradient))]
[JsonSerializable(typeof(APLInterfaceDetails))]
[JsonSerializable(typeof(APLInterfaceRuntime))]
[JsonSerializable(typeof(APLKeyboardHandler))]
[JsonSerializable(typeof(APLPageMoveHandler))]
[JsonSerializable(typeof(APLSkillRequest))]
[JsonSerializable(typeof(APLTransformer))]
[JsonSerializable(typeof(Layout))]
[JsonSerializable(typeof(IngredientListItem))]
[JsonSerializable(typeof(VideoSource))]
[JsonSerializable(typeof(TextTrack))]
[JsonSerializable(typeof(TimeText))]
// APL Enum types for proper serialization
[JsonSerializable(typeof(ContentDirection))]
[JsonSerializable(typeof(LayoutDirection))]
[JsonSerializable(typeof(ScrollDirection))]
[JsonSerializable(typeof(Snap))]
[JsonSerializable(typeof(TextOverflow))]
[JsonSerializable(typeof(AlexaImageAlignment))]
[JsonSerializable(typeof(AlexaImageAspectRatio))]
[JsonSerializable(typeof(AlexaTextWrapping))]
[JsonSerializable(typeof(MetadataPosition))]
[JsonSerializable(typeof(ProgressBarType))]
[JsonSerializable(typeof(RatingGraphicType))]
[JsonSerializable(typeof(RatingSlotMode))]
[JsonSerializable(typeof(SliderType))]
[JsonSerializable(typeof(SliderSize))]
[JsonSerializable(typeof(TimeTextDirection))]
[JsonSerializable(typeof(KeyboardType))]
[JsonSerializable(typeof(SubmitKeyType))]
[JsonSerializable(typeof(APLGradientType))]
[JsonSerializable(typeof(ControlMediaCommand))]
[JsonSerializable(typeof(RepeatMode))]
[JsonSerializable(typeof(ItemAlignment))]
[JsonSerializable(typeof(HighlightMode))]
public partial class AplJsonContext : JsonSerializerContext
{
}