using System.Text.Json.Serialization;
using AlexaVoxCraft.Model.Apl.Audio;
using AlexaVoxCraft.Model.Apl.Audio.Filters;
using AlexaVoxCraft.Model.Apl.Commands;
using AlexaVoxCraft.Model.Apl.Components;
using AlexaVoxCraft.Model.Apl.DataSources;
using AlexaVoxCraft.Model.Apl.DataStore;
using AlexaVoxCraft.Model.Apl.DataStore.PackageManager;
using AlexaVoxCraft.Model.Apl.Extensions.Backstack;
using AlexaVoxCraft.Model.Apl.Extensions.DataStore;
using AlexaVoxCraft.Model.Apl.Extensions.EntitySensing;
using AlexaVoxCraft.Model.Apl.Extensions.SmartMotion;
using AlexaVoxCraft.Model.Apl.Filters;
using AlexaVoxCraft.Model.Apl.Gestures;
using AlexaVoxCraft.Model.Apl.Operation;
using AlexaVoxCraft.Model.Apl.VectorGraphics;
using AlexaVoxCraft.Model.Apl.VectorGraphics.Filters;
using AlexaVoxCraft.Model.Request.Type;

namespace AlexaVoxCraft.Model.Apl.Serialization;

// Root types only - see AlexaVoxCraft.Model.Serialization.ModelContext for the same convention.
// This list was assembled from every RegisterTypeInfo<T>() call in APLSupport.Add() plus every
// typeof(...) target found in every BasePolymorphicConverter<T> subclass's DerivedTypes dictionary
// under src/AlexaVoxCraft.Model.Apl/JsonConverter, since BasePolymorphicConverter.Read dispatches via
// JsonSerializer.Deserialize(json, runtimeType, options) - every such runtime target needs an explicit
// entry here, not just the types that happen to appear as RegisterTypeInfo<T> calls.
[JsonSerializable(typeof(APLADocument))]
[JsonSerializable(typeof(APLAMultiChildComponent))]
[JsonSerializable(typeof(APLAbsoluteDimensionValue))]
[JsonSerializable(typeof(APLAction))]
[JsonSerializable(typeof(APLComponent))]
[JsonSerializable(typeof(APLComponentBase))]
[JsonSerializable(typeof(APLDimensionValue))]
[JsonSerializable(typeof(APLDocument))]
[JsonSerializable(typeof(APLDocumentBase))]
[JsonSerializable(typeof(APLDocumentLink))]
[JsonSerializable(typeof(APLKeyboardHandler))]
[JsonSerializable(typeof(APLPageMoveHandler))]
[JsonSerializable(typeof(APLTDocument))]
[JsonSerializable(typeof(APLTViewport))]
[JsonSerializable(typeof(APLViewport))]
[JsonSerializable(typeof(AVG))]
[JsonSerializable(typeof(AVGGroup))]
[JsonSerializable(typeof(AVGItem))]
[JsonSerializable(typeof(AVGPath))]
[JsonSerializable(typeof(AVGText))]
[JsonSerializable(typeof(ActionableComponent))]
[JsonSerializable(typeof(AlexaBackground))]
[JsonSerializable(typeof(AlexaButton))]
[JsonSerializable(typeof(AlexaCard))]
[JsonSerializable(typeof(AlexaCheckbox))]
[JsonSerializable(typeof(AlexaDetail))]
[JsonSerializable(typeof(AlexaDivider))]
[JsonSerializable(typeof(AlexaFooter))]
[JsonSerializable(typeof(AlexaGridList))]
[JsonSerializable(typeof(AlexaHeader))]
[JsonSerializable(typeof(AlexaHeadline))]
[JsonSerializable(typeof(AlexaIcon))]
[JsonSerializable(typeof(AlexaIconButton))]
[JsonSerializable(typeof(AlexaImage))]
[JsonSerializable(typeof(AlexaImageCaption))]
[JsonSerializable(typeof(AlexaImageList))]
[JsonSerializable(typeof(AlexaImageListBase))]
[JsonSerializable(typeof(AlexaImageListItem))]
[JsonSerializable(typeof(AlexaListItem))]
[JsonSerializable(typeof(AlexaLists))]
[JsonSerializable(typeof(AlexaOrdinal))]
[JsonSerializable(typeof(AlexaPageCounter))]
[JsonSerializable(typeof(AlexaPaginatedList))]
[JsonSerializable(typeof(AlexaPaginatedListItem))]
[JsonSerializable(typeof(AlexaPhoto))]
[JsonSerializable(typeof(AlexaProgressBar))]
[JsonSerializable(typeof(AlexaProgressBarRadial))]
[JsonSerializable(typeof(AlexaProgressDots))]
[JsonSerializable(typeof(AlexaRadioButton))]
[JsonSerializable(typeof(AlexaRating))]
[JsonSerializable(typeof(AlexaSlider))]
[JsonSerializable(typeof(AlexaSliderRadial))]
[JsonSerializable(typeof(AlexaSwipeToAction))]
[JsonSerializable(typeof(AlexaSwitch))]
[JsonSerializable(typeof(AlexaTextList))]
[JsonSerializable(typeof(AlexaTextListItem))]
[JsonSerializable(typeof(AlexaTextWrapping))]
[JsonSerializable(typeof(AlexaTransportControls))]
[JsonSerializable(typeof(AnimateItem))]
[JsonSerializable(typeof(AnimatedOpacity))]
[JsonSerializable(typeof(AnimatedProperty))]
[JsonSerializable(typeof(AnimatedTransform))]
[JsonSerializable(typeof(Audio.Audio))]
[JsonSerializable(typeof(AutoPage))]
[JsonSerializable(typeof(BackstackExtension))]
[JsonSerializable(typeof(Binding))]
[JsonSerializable(typeof(Blend))]
[JsonSerializable(typeof(Blur))]
[JsonSerializable(typeof(Clear))]
[JsonSerializable(typeof(ClearCommand))]
[JsonSerializable(typeof(ClearFocus))]
[JsonSerializable(typeof(Color))]
[JsonSerializable(typeof(CommandDefinition))]
[JsonSerializable(typeof(CommandsTarget))]
[JsonSerializable(typeof(Container))]
[JsonSerializable(typeof(ControlMedia))]
[JsonSerializable(typeof(CustomCommand))]
[JsonSerializable(typeof(CustomComponent))]
[JsonSerializable(typeof(DataStoreDeviceError))]
[JsonSerializable(typeof(DataStoreExtension))]
[JsonSerializable(typeof(DataStoreStorageError))]
[JsonSerializable(typeof(DeleteItem))]
[JsonSerializable(typeof(DeleteMultipleItems))]
[JsonSerializable(typeof(DoublePress))]
[JsonSerializable(typeof(DropShadow))]
[JsonSerializable(typeof(DynamicIndexList))]
[JsonSerializable(typeof(DynamicTokenList))]
[JsonSerializable(typeof(EditText))]
[JsonSerializable(typeof(EntitySensingExtension))]
[JsonSerializable(typeof(ExecuteCommandsDirective))]
[JsonSerializable(typeof(FadeIn))]
[JsonSerializable(typeof(FadeOut))]
[JsonSerializable(typeof(Finish))]
[JsonSerializable(typeof(FlexSequence))]
[JsonSerializable(typeof(FollowPrimaryUserCommand))]
[JsonSerializable(typeof(Frame))]
[JsonSerializable(typeof(GetObjectCommand))]
[JsonSerializable(typeof(GoBackCommand))]
[JsonSerializable(typeof(GoToCenterCommand))]
[JsonSerializable(typeof(Gradient))]
[JsonSerializable(typeof(Grayscale))]
[JsonSerializable(typeof(GridSequence))]
[JsonSerializable(typeof(Idle))]
[JsonSerializable(typeof(Image))]
[JsonSerializable(typeof(Import))]
[JsonSerializable(typeof(IngredientListItem))]
[JsonSerializable(typeof(AlexaVoxCraft.Model.Apl.Commands.InsertItem), TypeInfoPropertyName = "CommandsInsertItem")]
[JsonSerializable(typeof(AlexaVoxCraft.Model.Apl.Operation.InsertItem), TypeInfoPropertyName = "OperationInsertItem")]
[JsonSerializable(typeof(InsertMultipleItems))]
[JsonSerializable(typeof(KeyValueDataSource))]
[JsonSerializable(typeof(ListDataDirective))]
[JsonSerializable(typeof(ListDataSource))]
[JsonSerializable(typeof(LongPress))]
[JsonSerializable(typeof(Mixer))]
[JsonSerializable(typeof(Noise))]
[JsonSerializable(typeof(ObjectDataSource))]
[JsonSerializable(typeof(OpenURL))]
[JsonSerializable(typeof(Pager))]
[JsonSerializable(typeof(Parallel))]
[JsonSerializable(typeof(Parameter))]
[JsonSerializable(typeof(PlayMedia))]
[JsonSerializable(typeof(PlayNamedChoreoCommand))]
[JsonSerializable(typeof(PutNamespace))]
[JsonSerializable(typeof(PutObject))]
[JsonSerializable(typeof(PutObjectArray))]
[JsonSerializable(typeof(Reinflate))]
[JsonSerializable(typeof(RemoveItem))]
[JsonSerializable(typeof(RemoveNamespace))]
[JsonSerializable(typeof(Repeat))]
[JsonSerializable(typeof(ResponsiveTemplate))]
[JsonSerializable(typeof(Saturate))]
[JsonSerializable(typeof(Scroll))]
[JsonSerializable(typeof(ScrollToComponent))]
[JsonSerializable(typeof(ScrollToIndex))]
[JsonSerializable(typeof(ScrollView))]
[JsonSerializable(typeof(Select))]
[JsonSerializable(typeof(Selector))]
[JsonSerializable(typeof(SendEvent))]
[JsonSerializable(typeof(SendIndexListDataDirective))]
[JsonSerializable(typeof(SendTokenListDataDirective))]
[JsonSerializable(typeof(Sequence))]
[JsonSerializable(typeof(Sequencer))]
[JsonSerializable(typeof(Sequential))]
[JsonSerializable(typeof(SetFocus))]
[JsonSerializable(typeof(SetItem))]
[JsonSerializable(typeof(SetPage))]
[JsonSerializable(typeof(SetValue))]
[JsonSerializable(typeof(SetWakeWordResponseCommand))]
[JsonSerializable(typeof(SmartMotionExtension))]
[JsonSerializable(typeof(Spacer))]
[JsonSerializable(typeof(SpeakItem))]
[JsonSerializable(typeof(SpeakList))]
[JsonSerializable(typeof(Speech))]
[JsonSerializable(typeof(StopMotionCommand))]
[JsonSerializable(typeof(Style))]
[JsonSerializable(typeof(SwipeAway))]
[JsonSerializable(typeof(Tap))]
[JsonSerializable(typeof(Text))]
[JsonSerializable(typeof(TextBase))]
[JsonSerializable(typeof(TimeText))]
[JsonSerializable(typeof(TouchComponent))]
[JsonSerializable(typeof(TouchWrapper))]
[JsonSerializable(typeof(Trim))]
[JsonSerializable(typeof(TurnToPrimaryUserCommand))]
[JsonSerializable(typeof(UnwatchObjectCommand))]
[JsonSerializable(typeof(UpdateArrayBindingRangeCommand))]
[JsonSerializable(typeof(VectorGraphic))]
[JsonSerializable(typeof(Video))]
[JsonSerializable(typeof(VideoSource))]
[JsonSerializable(typeof(Volume))]
[JsonSerializable(typeof(WatchObjectCommand))]
[JsonSerializable(typeof(RenderDocumentDirective))]
[JsonSerializable(typeof(UpdateIndexListDataDirective))]
[JsonSerializable(typeof(UserEventRequest))]
[JsonSerializable(typeof(LoadIndexListDataRequest))]
[JsonSerializable(typeof(LoadTokenListDataRequest))]
[JsonSerializable(typeof(RuntimeErrorRequest))]
[JsonSerializable(typeof(UsagesInstalledRequest))]
[JsonSerializable(typeof(UsagesRemovedRequest))]
[JsonSerializable(typeof(UpdateRequest))]
[JsonSerializable(typeof(InstallationError))]
[JsonSerializable(typeof(DataStoreErrorRequest))]
[JsonSerializable(typeof(AudioLayout))]
[JsonSerializable(typeof(APLDocumentEnvironment))]
internal partial class AplModelContext : JsonSerializerContext
{
}
