name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
      - release/*
    tags:
      - v*
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'ROADMAP.md'
      - 'mkdocs.yml'
      - 'requirements.txt'
permissions: write-all
jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/package-build.yaml@v6.0
    with:
      hasTests: true
      useMtpRunner: true
      testDirectory: "test"
      dotnet-version: |
        8.0.x
        9.0.x
    secrets: inherit