name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: write-all
jobs:
  build:
    uses: ncipollina/devops-templates/.github/workflows/package-build.yaml@v3.0
    with:
      dotnet-version: "8.0.x"
    secrets: inherit