name: PR Build

on:
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/pr-build.yaml@v6.2
    with:
      solution: AlexaVoxCraft.slnx
      hasTests: true
      useMtpRunner: true
      testDirectory: "test"
      dotnetVersion: |
        8.0.x
        9.0.x
        10.0.x
      runCdk: false
    secrets: inherit