name: PR Build

on:
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  build:
    uses: ncipollina/devops-templates/.github/workflows/pr-build.yaml@v2.1
    with:
      solution: Disney.Trivia.Skill.sln
      hasTests: true
      dotnetVersion: "8.0.x"
      runCdk: false
    secrets: inherit